
  /*******************************************************************
  * Chirps.js
  * Generated by Backendless Corp.
  ********************************************************************/

const Utils = {
  isObject : obj => obj === Object(obj),
  isString : obj => Object.prototype.toString.call(obj).slice(8, -1) === 'String',
  isNumber : obj => Object.prototype.toString.call(obj).slice(8, -1) === 'Number',
  isBoolean: obj => Object.prototype.toString.call(obj).slice(8, -1) === 'Boolean',
  isDate   : obj => Object.prototype.toString.call(obj).slice(8, -1) === 'Date'
}

Backendless.APIServices.Chirps = {
  updateUser(updateRequest) {   
    if (!Utils.isObject(updateRequest)) {
      throw new Error('Invalid value for argument "updateRequest". Must be object value')
    }
    
    const args = updateRequest
    return Backendless.APIServices.invoke('Chirps', 'updateUser', args)
  }
}
